server:
  port: 8189
  connection-timeout: 300000
  http2:
    enabled: true
  compression:
    mime-types: text/html,text/plain,application/json
    enabled: true
    min-response-size: 1024

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: DigiLockerIssuerDemo

  datasource:
    url: jdbc:mariadb://localhost:3306/documentsdb
    username: root
    password: smart
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.document.issuer.demo: DEBUG

digilocker:
  issuer:
    apiKey: 6vQuJ5y+NPuZEVpXVflZQ9+VkqUKYjSvdBCNvu72